package com.workmemory.ai;

import java.util.List;

/**
 * Swappable AI backend. The product runs fully on the {@code local} provider
 * (deterministic, no API key) and can switch to OpenAI (gpt-4o-mini +
 * text-embedding-3-small) by setting workmemory.ai.provider=openai and a key.
 */
public interface AiProvider {

    /** Embedding dimension; must match the schema (1536). */
    int dimension();

    /** Provider name for diagnostics ("local" | "openai"). */
    String name();

    float[] embed(String text);

    List<float[]> embedBatch(List<String> texts);

    /** Whether answers are generated by a real LLM (true) or extractively (false). */
    boolean generative();

    /** Produce a grounded answer from the question and retrieved context snippets. */
    String generateAnswer(String question, List<String> contextSnippets);

    /** Short summary of a source's content. */
    String summarize(String text);

    /** Suggest 3-5 short lowercase tags relevant to the content. */
    List<String> suggestTags(String title, String text);
}
